export enum ErrorCode {
  ACCESS_TOKEN_NOT_FOUND = 1001,
  ACCESS_TOKEN_NOT_MATCH = 1002,
  AIRDROPS_DISABLED = 1003,
  ADDRESS_HAS_ALREADY_CLAIMED = 1004,
  INVALID_CREDENTIAL = 'INVALID_CREDENTIAL',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
}
